run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  # Only enable typecheck - compilation errors only
  enable:
    - typecheck
  disable-all: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
